AllCops:
  # rubocop requires ruby 2.2+
  # https://github.com/rubocop-hq/rubocop/pull/5990
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/LineLength:
  Exclude:
    - "spec/spec_helper.rb"

Style/HashSyntax:
  Exclude:
    - "Rakefile"
