AllCops:
  # rubocop requires ruby 2.1+ since v0.51.0
  # https://github.com/rubocop-hq/rubocop/commit/753227914c1ad311e6116311fc1ef76d9b0904dc
  TargetRubyVersion: 2.1

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/LineLength:
  Exclude:
    - "spec/spec_helper.rb"

Style/HashSyntax:
  Exclude:
    - "Rakefile"
